# Generated by Django 5.2.3 on 2025-08-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='host',
            field=models.CharField(default='db.ufazien.com', max_length=255),
        ),
    ]
