# Generated by Django 5.2.3 on 2025-08-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_alter_database_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('website_created', 'Website Created'), ('website_updated', 'Website Updated'), ('website_deployed', 'Website Deployed'), ('website_deleted', 'Website Deleted'), ('database_created', 'Database Created'), ('database_updated', 'Database Updated'), ('database_deleted', 'Database Deleted'), ('database_password_changed', 'Database Password Changed'), ('domain_added', 'Domain Added'), ('domain_updated', 'Domain Updated'), ('domain_deleted', 'Domain Deleted'), ('ssl_issued', 'SSL Certificate Issued'), ('ssl_created', 'SSL Certificate Created'), ('ssl_updated', 'SSL Certificate Updated'), ('ssl_deleted', 'SSL Certificate Deleted'), ('ssl_issue_failed', 'SSL Certificate Issue Failed'), ('subscription_upgraded', 'Subscription Upgraded'), ('subscription_cancelled', 'Subscription Cancelled'), ('backup_created', 'Backup Created'), ('backup_restored', 'Backup Restored')], max_length=50),
        ),
    ]
