# Generated by Django 5.2.3 on 2025-08-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_alter_activitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='connection_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='database',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='database',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
