# Generated by Django 5.2.3 on 2026-08-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosting", "0004_database_connection_info_database_error_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("developer", "Developer"),
                    ("pro", "Pro"),
                    ("special", "Special"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
