# Generated by Django 5.2.3 on 2026-08-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0005_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteanalytics',
            name='bandwidth_used',
            field=models.BigIntegerField(default=0),
        ),
    ]
