# Generated by Django 5.2.3 on 2026-08-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0006_websiteanalytics_bandwidth_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteanalytics',
            name='devices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
