# Generated by Django 5.2.3 on 2026-08-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0007_websiteanalytics_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandwidthusage',
            name='bandwidth_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
