# Generated by Django 5.2.3 on 2025-11-02 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_security_notification_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug Report'), ('vulnerability', 'Security Vulnerability'), ('feature', 'Feature Request'), ('improvement', 'Improvement Suggestion'), ('share_me_on_testimonials', 'Share Me on Testimonials'), ('general', 'General Feedback')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_feedbac_user_id_2f606a_idx'), models.Index(fields=['status'], name='api_feedbac_status_693c36_idx')],
            },
        ),
    ]
