# Generated by Django 5.2.3 on 2025-07-15 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('average', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldgrade',
            name='grade',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
    ]
