# Generated by Django 5.2.3 on 2025-07-15 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('average', '0002_alter_fieldgrade_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='averageschema',
            name='original_schema',
            field=models.ForeignKey(blank=True, help_text='Reference to original schema if this is a saved copy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='average.averageschema'),
        ),
        migrations.CreateModel(
            name='SavedSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('original_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='average.averageschema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_schemas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'original_schema')},
            },
        ),
    ]
