services:
  hosting:
    image: nginx:alpine
    container_name: ufazien-hosting
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /etc/data/hosting:/var/www/html
      - ./nginx/hosting.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - internal

  php:
    build: .
    container_name: ufazien-php-fpm
    restart: unless-stopped
    volumes:
      - /etc/data/hosting:/var/www/html
    environment:
      PHP_FPM_PM_MAX_CHILDREN: "5"
    networks:
      - internal


networks:
  internal:
    driver: bridge