# Generated by Django 5.2.3 on 2025-07-07 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_options_blogpost_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.blogpost'),
        ),
    ]
