# Generated by Django 5.2.3 on 2026-08-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_blogpost_created_at_published_at_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("unlisted", "Unlisted"),
                    ("followers", "Followers only"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
