# Generated by Django 5.2.3 on 2026-08-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lobbymember",
            name="can_share_screen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lobbymember",
            name="is_muted",
            field=models.BooleanField(default=False),
        ),
    ]
