# Generated by Django 5.2.3 on 2026-08-11 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_lobbymember_can_share_screen_lobbymember_is_muted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="playerposition",
            name="activity",
            field=models.CharField(
                choices=[
                    ("standing", "Standing"),
                    ("sitting", "Sitting"),
                    ("waving", "Waving"),
                    ("clapping", "Clapping"),
                    ("hand_raised", "Hand raised"),
                    ("pointing", "Pointing"),
                ],
                default="standing",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="playerposition",
            name="heading",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playerposition",
            name="seat",
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddConstraint(
            model_name="playerposition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("seat__isnull", False)),
                fields=("lobby", "seat"),
                name="one_occupant_per_seat",
            ),
        ),
    ]
