# Generated by Django 5.2.3 on 2026-08-11 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_playerposition_activity_playerposition_heading_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="playerposition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("seat__isnull", True),
                    models.Q(("seat", ""), _negated=True),
                    _connector="OR",
                ),
                name="seat_is_null_or_named",
            ),
        ),
    ]
