# Generated by Django 5.2.3 on 2026-08-11 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_playerposition_seat_is_null_or_named"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampusProp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prop", models.CharField(max_length=48)),
                ("room", models.CharField(blank=True, max_length=50, null=True)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["prop"],
            },
        ),
        migrations.CreateModel(
            name="RoomLight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.CharField(max_length=50)),
                ("on", models.BooleanField(default=True)),
                ("changed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["room"],
            },
        ),
        migrations.AddField(
            model_name="playerposition",
            name="holding",
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name="playerposition",
            name="activity",
            field=models.CharField(
                choices=[
                    ("standing", "Standing"),
                    ("sitting", "Sitting"),
                    ("leaning", "Leaning"),
                    ("waving", "Waving"),
                    ("clapping", "Clapping"),
                    ("hand_raised", "Hand raised"),
                    ("pointing", "Pointing"),
                ],
                default="standing",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="playerposition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("holding__isnull", False)),
                fields=("lobby", "holding"),
                name="one_holder_per_prop",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerposition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("holding__isnull", True),
                    models.Q(("holding", ""), _negated=True),
                    _connector="OR",
                ),
                name="holding_is_null_or_named",
            ),
        ),
        migrations.AddField(
            model_name="campusprop",
            name="lobby",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="props",
                to="game.lobby",
            ),
        ),
        migrations.AddField(
            model_name="roomlight",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roomlight",
            name="lobby",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_lights",
                to="game.lobby",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campusprop",
            unique_together={("lobby", "prop")},
        ),
        migrations.AlterUniqueTogether(
            name="roomlight",
            unique_together={("lobby", "room")},
        ),
    ]
