# Generated by Django 5.2.3 on 2026-08-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_campusprop_roomlight_playerposition_holding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerposition',
            name='elevation',
            field=models.FloatField(default=0.0),
        ),
    ]
