# Generated by Django 5.2.3 on 2026-08-17 07:29

from django.db import migrations


class Migration(migrations.Migration):
    """
    Drops StudyRoom, which no player could ever occupy.

    Occupancy compared a room *name* against `PlayerPosition.current_room`,
    which holds a building *id* — the campus sends `String(building.id)`
    deliberately, so that two buildings sharing a name do not share a
    projector. `"Library"` never equalled `"1"`, so the count was
    structurally zero and the API served that zero to every client.

    Nothing is lost with it. The four rows created on every lobby carried
    coordinates from the 2D sprite campus (`x: 100, y: 100, width: 200`) that
    correspond to nothing in the 3D one, they were rendered nowhere, and the
    rooms inside the building already do this job through `current_room` —
    scoping chat, the projector and who you can see. See #144.
    """


    dependencies = [
        ('game', '0008_alter_chatmessage_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyRoom',
        ),
    ]
