# Generated by Django 5.2.3 on 2026-08-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_lobbymember_is_online_lobbymember_connections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbymember',
            name='can_kick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lobbymember',
            name='can_manage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lobbymember',
            name='can_mute_others',
            field=models.BooleanField(default=False),
        ),
    ]
