# Generated by Django 5.2.3 on 2025-07-16 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInputState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_tab', models.CharField(choices=[('semester', 'Semester'), ('yearly', 'Yearly')], default='semester', max_length=10)),
                ('semester_data', models.JSONField(blank=True, default=list)),
                ('yearly_data', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpa_input_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Input State',
                'verbose_name_plural': 'User Input States',
            },
        ),
    ]
