# Generated by Django 5.2.3 on 2025-07-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0002_userinputstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinputstate',
            name='active_tab',
            field=models.CharField(choices=[('semester', 'Semester'), ('yearly', 'Yearly'), ('history', 'History')], default='semester', max_length=20),
        ),
    ]
