# Generated by Django 5.2.3 on 2026-08-06 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpa", "0003_alter_userinputstate_active_tab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursegrade",
            name="credits",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(60),
                ]
            ),
        ),
    ]
