/**
 * The real district around 183 Nizami Street, as data.
 *
 * GENERATED by `scripts/build-district.mjs`. Do not edit by hand — re-run the
 * generator, which documents the Overpass query it was built from.
 *
 * Street centrelines and building footprints are OpenStreetMap data, projected
 * onto a local tangent plane at the university, rotated so Nizami Street runs
 * along the world X axis, and translated so the real UFAZ footprint sits on the
 * landmark. Distances are metres and match the world's scale, so the block
 * across the street is as far away here as it is in Baku.
 *
 * Only UFAZ's own side of Nizami Street is included. The far side is where the
 * invented campus stands — the library, the labs, the amphitheatre and the
 * sports hall are not real buildings and never were, and this change did not
 * set out to delete them. So the city is real to the north of the street and
 * ours to the south, and the street is the seam.
 *
 * Rotation applied: 156.23°.
 *
 * Source data © OpenStreetMap contributors, available under the Open Database
 * Licence (https://www.openstreetmap.org/copyright). Heights come from
 * `building:levels` where the map records it and are estimated otherwise, so
 * treat the skyline as indicative and the footprints as accurate.
 */

/** A footprint, as a closed ring of [x, z] in world metres. */
export type Footprint = readonly (readonly [number, number])[]

/** How a block's facade is drawn. */
export type DistrictStyle = 'limestone' | 'tower' | 'infill'

export interface DistrictBuilding {
  footprint: Footprint
  /** Eaves height in metres. */
  height: number
  style: DistrictStyle
  /** Present only where OSM names the building. */
  name?: string
  /**
   * `osm` is a surveyed footprint. `infill` is a terrace block standing on a
   * frontage the map leaves blank — the streets here are mapped in full and the
   * buildings along them are not, and a road through an empty lot is a worse
   * likeness of this quarter than a terrace is.
   */
  source: 'osm' | 'infill'
}

export interface DistrictStreet {
  /** Centreline, as [x, z] in world metres. */
  points: readonly (readonly [number, number])[]
  /** Kerb to kerb, in metres. */
  width: number
  name?: string
  kind: 'road' | 'pedestrian'
}

export const DISTRICT_BUILDINGS: readonly DistrictBuilding[] = [
  { footprint: [[-209.8,-130.5],[-208.8,-115.3],[-216.6,-114.7],[-217.5,-130]], height: 3.6, style: 'infill', source: 'osm' },
  { footprint: [[-113,-126],[-112.6,-115.6],[-122.1,-115.1],[-122.5,-125.6]], height: 3.6, style: 'infill', source: 'osm' },
  { footprint: [[-109.5,-159.4],[-108.9,-148.6],[-116.8,-148.1],[-116.3,-139.5],[-108.6,-140],[-108.1,-130.2],[-123,-129.3],[-124.5,-158.6]], height: 10.8, style: 'limestone', source: 'osm' },
  { footprint: [[-99.8,-175],[-99.3,-163.2],[-124.7,-162],[-125.2,-173.8]], height: 10.8, style: 'limestone', source: 'osm' },
  { footprint: [[-82.1,-123.1],[-81.3,-110.3],[-92.6,-109.6],[-93.4,-122.3]], height: 3.6, style: 'infill', source: 'osm' },
  { footprint: [[-74.4,-176.9],[-73.7,-166.5],[-77.7,-166.2],[-77.2,-160],[-81.1,-159.7],[-80.4,-148.5],[-73.2,-149],[-70.1,-102.7],[-78.6,-102.1],[-80.4,-128.2],[-88,-127.7],[-90.5,-164.3],[-95.3,-164],[-96.1,-175.4]], height: 10.8, style: 'limestone', source: 'osm' },
  { footprint: [[-61.3,-177.7],[-60.1,-152.5],[-64.7,-152.3],[-64.5,-148.8],[-53.6,-149.4],[-52.9,-133.9],[-51.3,-100],[-59.9,-99.6],[-61.4,-132.8],[-69.6,-132.3],[-71.7,-177.2]], height: 10.8, style: 'limestone', source: 'osm' },
  { footprint: [[81.9,-96],[82.6,-71],[49.9,-70],[48.9,-108.6],[72.4,-109.3],[72.7,-95.7]], height: 3.6, style: 'infill', source: 'osm' },
  { footprint: [[97.3,-124],[97.9,-106.8],[86.5,-106.3],[85.9,-123.5]], height: 3.6, style: 'infill', source: 'osm' },
  { footprint: [[187.9,-137.7],[189.8,-80.7],[158.2,-79.5],[90.1,-76.8],[89.7,-90.6],[158,-93.3],[176.4,-94],[175,-137.2]], height: 14.4, style: 'limestone', source: 'osm' },
  { footprint: [[201.5,-181.4],[201,-195.9],[177.3,-194.9],[177.9,-178.2],[178,-173.9],[186.6,-174.2],[186.4,-180.8]], height: 14.4, style: 'limestone', source: 'osm' },
  { footprint: [[203,-138.3],[201.5,-181.4],[186.4,-180.8],[186.6,-174.2],[187.9,-137.7]], height: 14.4, style: 'limestone', source: 'osm' },
  { footprint: [[-155.77304288624316,-224.4],[-141.62695711375682,-224.4],[-141.62695711375682,-202.4],[-155.77304288624316,-202.4]], height: 21.6, style: 'limestone', source: 'infill' },
  { footprint: [[-152.17304288624317,-177.6],[-138.02695711375682,-177.6],[-138.02695711375682,-155.6],[-152.17304288624317,-155.6]], height: 18, style: 'limestone', source: 'infill' },
  { footprint: [[-128.3108883907472,-226.4],[-103.68911160925278,-226.4],[-103.68911160925278,-204.4],[-128.3108883907472,-204.4]], height: 14.4, style: 'limestone', source: 'infill' },
  { footprint: [[-76.21088839074721,-229.2],[-51.589111609252775,-229.2],[-51.589111609252775,-207.2],[-76.21088839074721,-207.2]], height: 21.6, style: 'limestone', source: 'infill' },
  { footprint: [[-24.01088839074722,-232],[0.6108883907472222,-232],[0.6108883907472222,-210],[-24.01088839074722,-210]], height: 14.4, style: 'limestone', source: 'infill' },
  { footprint: [[-47.510888390747226,-183.7],[-22.88911160925278,-183.7],[-22.88911160925278,-161.7],[-47.510888390747226,-161.7]], height: 18, style: 'limestone', source: 'infill' },
  { footprint: [[4.589111609252777,-186.5],[29.210888390747222,-186.5],[29.210888390747222,-164.5],[4.589111609252777,-164.5]], height: 14.4, style: 'limestone', source: 'infill' },
  { footprint: [[46.45594190568663,-235.5],[67.14405809431337,-235.5],[67.14405809431337,-213.5],[46.45594190568663,-213.5]], height: 18, style: 'limestone', source: 'infill' },
  { footprint: [[49.255941905686626,-188.6],[69.94405809431338,-188.6],[69.94405809431338,-166.6],[49.255941905686626,-166.6]], height: 21.6, style: 'limestone', source: 'infill' },
  { footprint: [[90.5325536645547,-238.4],[116.86744633544531,-238.4],[116.86744633544531,-216.4],[90.5325536645547,-216.4]], height: 18, style: 'limestone', source: 'infill' },
  { footprint: [[146.1325536645547,-242],[172.46744633544532,-242],[172.46744633544532,-220],[146.1325536645547,-220]], height: 18, style: 'limestone', source: 'infill' },
  { footprint: [[93.63255366455469,-191.5],[119.9674463354453,-191.5],[119.9674463354453,-169.5],[93.63255366455469,-169.5]], height: 14.4, style: 'limestone', source: 'infill' },
  { footprint: [[149.2325536645547,-195.1],[175.5674463354453,-195.1],[175.5674463354453,-173.1],[149.2325536645547,-173.1]], height: 21.6, style: 'limestone', source: 'infill' },
  { footprint: [[46.5,-155.2754123641219],[68.5,-155.2754123641219],[68.5,-132.5245876358781],[46.5,-132.5245876358781]], height: 18, style: 'limestone', source: 'infill' },
  { footprint: [[3.5,-154.8754123641219],[25.5,-154.8754123641219],[25.5,-132.1245876358781],[3.5,-132.1245876358781]], height: 14.4, style: 'limestone', source: 'infill' },
  { footprint: [[3.6999999999999993,-130.5754123641219],[25.7,-130.5754123641219],[25.7,-107.8245876358781],[3.6999999999999993,-107.8245876358781]], height: 18, style: 'limestone', source: 'infill' },
  { footprint: [[5.100000000000001,-213.80456052566464],[27.1,-213.80456052566464],[27.1,-201.59543947433534],[5.100000000000001,-201.59543947433534]], height: 18, style: 'limestone', source: 'infill' },
  { footprint: [[-173.8,-149.92591844892007],[-151.8,-149.92591844892007],[-151.8,-122.67408155107995],[-173.8,-122.67408155107995]], height: 18, style: 'limestone', source: 'infill' },
]

export const DISTRICT_STREETS: readonly DistrictStreet[] = [
  { points: [[-203.4,-174.5],[-202.8,-168.2],[-196.9,-75.9]], width: 11, kind: 'road' },
  { points: [[-2.8,-130.2],[-22.3,-130.5]], width: 6, kind: 'road' },
  { points: [[35.9,-155.8],[28.6,-155.7],[1.3,-154.8],[-1.7,-153.7],[-2.9,-151.3],[-2.8,-130.2],[-2.6,-102]], width: 6, kind: 'road' },
  { points: [[91.4,-203],[91.2,-215.1]], width: 6, kind: 'road' },
  { points: [[158,-93.3],[158.2,-79.5]], width: 6, kind: 'road' },
  { points: [[158.1,-97.2],[158,-93.3]], width: 6, kind: 'road' },
  { points: [[158.2,-79.5],[158.7,-73],[159.2,-64.6]], width: 6, kind: 'road' },
  { points: [[163.4,-118],[139.9,-115.3],[134.9,-114.8],[131.7,-112.2],[130.6,-108.5],[131.3,-96.3]], width: 6, kind: 'road' },
  { points: [[163.5,-127.9],[163.4,-118],[163.3,-103.5],[162.5,-99.3],[158.1,-97.2],[131.3,-96.3],[88.7,-94.2]], width: 6, kind: 'road' },
  { points: [[169.2,-46],[168.4,-54],[168.4,-54.7],[168.4,-56.8],[168.4,-65]], width: 6, kind: 'road' },
  { points: [[172.6,-46.4],[170.9,-46.2],[169.2,-46]], width: 6, kind: 'road' },
  { points: [[-165.8,-188.8],[-154.7,-189.4],[-139.1,-190.6]], width: 15, kind: 'road', name: "28 May küçəsi" },
  { points: [[-139.1,-190.6],[-127.8,-191.2],[28.7,-199.7]], width: 15, kind: 'road', name: "28 May küçəsi" },
  { points: [[28.7,-199.7],[37.3,-200.1],[44,-200.5],[47.1,-200.4]], width: 15, kind: 'road', name: "28 May küçəsi" },
  { points: [[47.1,-200.4],[91.4,-203],[202.5,-210.3]], width: 15, kind: 'road', name: "28 May küçəsi" },
  { points: [[202.5,-210.3],[210,-210.6]], width: 15, kind: 'road', name: "28 May küçəsi" },
  { points: [[210,-210.6],[219.7,-211.3]], width: 15, kind: 'road', name: "28 May küçəsi" },
  { points: [[210,-210.6],[210.3,-200.8]], width: 19, kind: 'road', name: "Azadlıq prospekti" },
  { points: [[210.3,-200.8],[211.1,-78.2]], width: 19, kind: 'road', name: "Azadlıq prospekti" },
  { points: [[210.5,-230.7],[210,-210.6]], width: 19, kind: 'road', name: "Azadlıq prospekti" },
  { points: [[211.1,-78.2],[210.9,-66.6],[210.7,-57.7]], width: 19, kind: 'road', name: "Azadlıq prospekti" },
  { points: [[36,-189.7],[35.9,-155.8],[36.3,-107.3],[37,-72.5]], width: 11, kind: 'road', name: "Fikrət Əmirov küçəsi" },
  { points: [[37,-72.5],[36.8,-59],[37.1,-50.7]], width: 11, kind: 'road', name: "Fikrət Əmirov küçəsi" },
  { points: [[37.3,-200.1],[36,-189.7]], width: 11, kind: 'road', name: "Fikrət Əmirov küçəsi" },
  { points: [[37.8,-213.8],[37.3,-200.1]], width: 11, kind: 'road', name: "Fikrət Əmirov küçəsi" },
  { points: [[-127.5,-52.3],[-140,-50.9],[-151.5,-50.4]], width: 11, kind: 'road', name: "Nizami küçəsi" },
  { points: [[29.3,-58.6],[-127.5,-52.3]], width: 11, kind: 'road', name: "Nizami küçəsi" },
  { points: [[45.2,-59.4],[36.8,-59],[29.3,-58.6]], width: 11, kind: 'road', name: "Nizami küçəsi" },
  { points: [[201,-66.5],[170.8,-65.1],[168.4,-65],[159.2,-64.6],[86,-61.4],[45.2,-59.4]], width: 11, kind: 'road', name: "Nizami küçəsi" },
  { points: [[220.8,-66.9],[210.9,-66.6],[201,-66.5]], width: 11, kind: 'road', name: "Nizami küçəsi" },
  { points: [[231.9,-67],[220.8,-66.9]], width: 11, kind: 'road', name: "Nizami küçəsi" },
  { points: [[-140.1,-64.2],[-140,-50.9]], width: 15, kind: 'road', name: "Puşkin küçəsi" },
  { points: [[-139.9,-209],[-139.1,-190.6]], width: 15, kind: 'road', name: "Puşkin küçəsi" },
  { points: [[-139.1,-190.6],[-138.8,-182.8],[-138.8,-179.2],[-140.1,-64.2]], width: 15, kind: 'road', name: "Puşkin küçəsi" },
]

/** Shown in the campus credits, because ODbL requires the attribution. */
export const DISTRICT_ATTRIBUTION = '© OpenStreetMap contributors'
