"""
Django settings for ufazien project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse, parse_qsl
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-default-key-for-development")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").strip().lower() in ("true", "1", "yes", "on")
# Fix ALLOWED_HOSTS with fallback
ALLOWED_HOSTS_ENV = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,testserver,api.ufazien.com")
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'channels',
    'auditlog',
    # Api Docs
    'drf_spectacular',
    'drf_spectacular_sidecar',
    # Local apps
    'ufazien.apps.UfazienConfig',  # Custom app config for auditlog
    'api',
    'blog',
    'users',
    'average',
    'gpa',
    'game',
    'ai_tools',
    'hosting',
    'community',
    'schedule',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



# Comma-separated env override; the list below is the fallback default.
def _env_list(name, default):
    raw = os.getenv(name, "")
    return [v.strip() for v in raw.split(",") if v.strip()] or default


CORS_ALLOWED_ORIGINS = _env_list("DJANGO_CORS_ALLOWED_ORIGINS", [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://ufazien.com",
    "https://ufazien.com",
    "http://api.ufazien.com",
    "https://api.ufazien.com",
])

CORS_ALLOW_CREDENTIALS = True

# Allow all headers for multipart/form-data uploads
CORS_ALLOW_ALL_HEADERS = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_RATES': {
        'feedback': '12/hour',  # 12 per hour = 1 per 5 minutes
    },
    'PAGE_SIZE': 10,  # Default page size for pagination
}

# REST_AUTH = {
#     'USE_JWT': True,
#     'JWT_AUTH_COOKIE': 'access',
#     'JWT_AUTH_REFRESH_COOKIE': 'refresh',
# }

SPECTACULAR_SETTINGS = {
    'TITLE': 'Ufazien API',
    'DESCRIPTION': 'API documentation for Ufazien project',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',  
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
}


ROOT_URLCONF = 'ufazien.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ufazien.wsgi.application'
ASGI_APPLICATION = 'ufazien.asgi.application'

# Makes `manage.py runserver` serve WebSockets.
#
# Channels 4 moved the ASGI-aware runserver out of `channels` and into
# `daphne`, and it only takes effect when `daphne` is listed *before*
# `staticfiles`. Without it `runserver` is Django's ordinary WSGI server,
# `ASGI_APPLICATION` is never consulted, and every handshake to
# `/ws/game/lobby/…` returns 404 — no positions, no chat, no seating, no
# props, no lift. The campus loads and you are alone in it, which reads as a
# bug in the game rather than a missing dependency. Following CONTRIBUTING.md
# to the letter produced exactly that.
#
# Conditional because it is a development dependency: `requirements-dev.txt`
# installs daphne (the WebSocket tests need it), `requirements.txt` does not,
# and production serves ASGI through uvicorn where none of this applies.
# Listing it unconditionally would stop the deployed app booting.
try:
    import daphne  # noqa: F401
except ImportError:
    pass
else:
    INSTALLED_APPS.insert(0, 'daphne')


# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Channel Layers Configuration
#
# InMemoryChannelLayer only reaches consumers inside one process, so group
# sends never cross workers: two students on different uvicorn workers cannot
# see each other's chat messages or campus movement. It survives here only as
# the fallback for local development and the test suite, where a single
# process is the whole world and requiring Redis would be friction.
REDIS_URL = os.getenv("REDIS_URL", "")

if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


if os.getenv("ENVIRONMENT") == "production":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'ufazien_test'),
            'USER': os.getenv('DB_USER', 'ufazien_test_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'test_password'),
            'HOST': os.getenv('DB_HOST', 'db.ufazien.com'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# NEON SERVERLESS DATABASE CONFIGURATION

# Replace the DATABASES section of your settings.py with this
# tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': tmpPostgres.path.replace('/', ''),
#         'USER': tmpPostgres.username,
#         'PASSWORD': tmpPostgres.password,
#         'HOST': tmpPostgres.hostname,
#         'PORT': 5432,
#         'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": MEDIA_ROOT,
        },
    },
    "private": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": MEDIA_ROOT / "private",
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Object storage. Everything above is the local-disk fallback used by the test
# suite and by anyone running the app without MinIO; setting the endpoint is
# what moves uploads off the container's filesystem.
#
# The endpoint is the public domain, not the internal container address. A
# presigned URL carries a signature bound to the host it was signed for, so
# signing against an internal hostname yields URLs that fail as soon as a
# browser requests them from the public domain.
AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL", "").rstrip("/")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "")
AWS_PUBLIC_BUCKET_NAME = os.getenv("AWS_PUBLIC_BUCKET_NAME", "ufazien-public")
AWS_PRIVATE_BUCKET_NAME = os.getenv("AWS_PRIVATE_BUCKET_NAME", "ufazien-private")
AWS_PRIVATE_URL_EXPIRY_SECONDS = int(os.getenv("AWS_PRIVATE_URL_EXPIRY_SECONDS", "3600"))
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1")
# MinIO serves many buckets from one hostname, so the bucket stays in the path
# rather than becoming a subdomain.
AWS_S3_ADDRESSING_STYLE = "path"
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

USE_OBJECT_STORAGE = bool(AWS_S3_ENDPOINT_URL and AWS_ACCESS_KEY_ID)

if USE_OBJECT_STORAGE:
    STORAGES["default"] = {"BACKEND": "api.storages.PublicMediaStorage"}
    STORAGES["private"] = {"BACKEND": "api.storages.PrivateMediaStorage"}
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_PUBLIC_BUCKET_NAME}/"
elif os.getenv("ENVIRONMENT") == "production":
    # Falling back to the filesystem in production is silent data loss: the
    # container no longer bind-mounts a media directory, so uploads would land
    # on the container's own disk and disappear at the next redeploy, with
    # nothing logged and no error for the user. Refuse to boot instead.
    raise ImproperlyConfigured(
        "Object storage is not configured but ENVIRONMENT=production. "
        "Set AWS_S3_ENDPOINT_URL and AWS_ACCESS_KEY_ID, or uploads will be "
        "written to the container filesystem and lost on redeploy."
    )

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
AUTH_USER_MODEL = 'users.User'

# Email settings for production (update these for production use)
DEFAULT_FROM_EMAIL = 'ufazien@ufazien.com'
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = os.getenv('EMAIL_PORT', 587)
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# Push notification settings (VAPID keys for web push)
VAPID_PUBLIC_KEY = os.getenv('VAPID_PUBLIC_KEY_PEM', '')
VAPID_PUBLIC_KEY_B64 = os.getenv('VAPID_PUBLIC_KEY_B64', '')

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=1440),    # 1 day
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),      # 1 week
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    # ...
}

# Azure OpenAI Configuration
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION", "2024-02-15-preview")
AZURE_OPENAI_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME", "gpt-4o-mini")

# Celery Configuration
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_BROKER_URL = "memory://"
CELERY_RESULT_BACKEND = "cache+memory://"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

# Celery Beat schedule: run storage computation periodically.
# By default this schedules compute_storage_for_all_users to run hourly.
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'compute-storage-every-hour': {
        'task': 'hosting.tasks.compute_storage_for_all_users',
    # run every 10 minutes
    'schedule': crontab(minute='*/1'),
        'options': {'queue': 'maintenance'},
    },
}

# AI Tools Rate Limiting
DEFAULT_RATE_LIMIT = int(os.getenv("DEFAULT_RATE_LIMIT", "100"))
PREMIUM_RATE_LIMIT = int(os.getenv("PREMIUM_RATE_LIMIT", "1000"))

# Django Auditlog Configuration
AUDITLOG_INCLUDE_ALL_MODELS = True  # Log all model changes
AUDITLOG_EXCLUDE_TRACKING_FIELDS = ['created_at', 'updated_at']  # Exclude timestamp fields
AUDITLOG_DISABLE_ON_RAW_SAVE = False  # Track raw saves too
AUDITLOG_USE_CONNECTION_HANDLING = True  # Better performance
AUDITLOG_READONLY_EVENTS = True  # Track read events
AUDITLOG_READONLY_EVENTS_ACTIONS = ['read']  # Track read actions


# Admin credentials for remote DB provisioning (used by provisioning Celery task)
# Example: set DB_ADMIN_POSTGRES_USER, DB_ADMIN_POSTGRES_PASSWORD in environment
DB_ADMIN = {
    'postgresql': {
        'host': os.getenv('DB_ADMIN_POSTGRES_HOST', 'postgres.ufazien.com'),
        'port': int(os.getenv('DB_ADMIN_POSTGRES_PORT', '5433')),
        'user': os.getenv('DB_ADMIN_POSTGRES_USER', ''),
        'password': os.getenv('DB_ADMIN_POSTGRES_PASSWORD', ''),
        # SSL intentionally disabled for provisioning per project requirement
    },
    'mysql': {
        'host': os.getenv('DB_ADMIN_MYSQL_HOST', 'mysql.ufazien.com'),
        'port': int(os.getenv('DB_ADMIN_MYSQL_PORT', '3306')),
        'user': os.getenv('DB_ADMIN_MYSQL_USER', ''),
        'password': os.getenv('DB_ADMIN_MYSQL_PASSWORD', ''),
    }
}
# Cloudflare / Traefik Cookie & Proxy Fixes
CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS", [
    "https://api.ufazien.com",
    "https://ufazien.com",
    "https://www.ufazien.com",
])

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None"

SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "None"

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# Hosting analytics.
#
# nginx writes one JSON object per request for every user site (see
# `hosting/nginx/hosting.conf`), and `manage.py aggregate_access_logs` rolls
# those into a day per site. Nothing tracked user traffic before that: the
# analytics table's only writer was a webhook nothing called, so the page fell
# back to invented figures.
HOSTING_ACCESS_LOGS = os.getenv("HOSTING_ACCESS_LOGS", "/var/log/hosting/access.log*")

# The domain user sites hang off. A log line names its site by host, and
# `Website.name` is the subdomain.
HOSTING_BASE_DOMAIN = os.getenv("HOSTING_BASE_DOMAIN", "ufazien.com")

# Signs the analytics webhook. Unset, the endpoint refuses everything rather
# than accepting anything: a subdomain says which site a payload is for, it
# does not prove who sent it.
HOSTING_WEBHOOK_SECRET = os.getenv("HOSTING_WEBHOOK_SECRET", "")
