# Generated by Django 5.2.3 on 2025-07-19 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIToolConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('humanizer', 'Text Humanizer'), ('paraphraser', 'AI Paraphraser'), ('summarizer', 'Text Summarizer'), ('grammar_checker', 'Grammar Assistant')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_input_length', models.IntegerField(default=10000)),
                ('rate_limit_per_hour', models.IntegerField(default=100)),
                ('priority', models.IntegerField(default=1)),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Tool Configuration',
                'verbose_name_plural': 'AI Tool Configurations',
            },
        ),
        migrations.CreateModel(
            name='AITask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_type', models.CharField(choices=[('humanizer', 'Text Humanizer'), ('paraphraser', 'AI Paraphraser'), ('summarizer', 'Text Summarizer'), ('grammar_checker', 'Grammar Assistant')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('input_text', models.TextField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('output_text', models.TextField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('input_word_count', models.IntegerField(default=0)),
                ('input_char_count', models.IntegerField(default=0)),
                ('output_word_count', models.IntegerField(default=0)),
                ('output_char_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HumanizerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_style', models.CharField(choices=[('natural', 'Natural'), ('academic', 'Academic'), ('casual', 'Casual'), ('professional', 'Professional'), ('creative', 'Creative')], default='natural', max_length=15)),
                ('preserve_formatting', models.BooleanField(default=True)),
                ('target_tone', models.CharField(blank=True, max_length=50)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='humanizer_details', to='ai_tools.aitask')),
            ],
            options={
                'verbose_name': 'Humanizer Task',
                'verbose_name_plural': 'Humanizer Tasks',
            },
        ),
        migrations.CreateModel(
            name='UserUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humanizer_count', models.IntegerField(default=0)),
                ('paraphraser_count', models.IntegerField(default=0)),
                ('summarizer_count', models.IntegerField(default=0)),
                ('grammar_checker_count', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('total_words_processed', models.IntegerField(default=0)),
                ('total_chars_processed', models.IntegerField(default=0)),
                ('first_use', models.DateTimeField(auto_now_add=True)),
                ('last_use', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Usage Stats',
                'verbose_name_plural': 'User Usage Stats',
            },
        ),
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['user', 'tool_type'], name='ai_tools_ai_user_id_c62dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['status'], name='ai_tools_ai_status_b951a8_idx'),
        ),
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['created_at'], name='ai_tools_ai_created_ff5b9a_idx'),
        ),
    ]
