# Generated by Django 5.2.3 on 2026-08-11 17:36

import api.attachments
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_postattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmessage",
            name="file_attachment",
            field=models.FileField(
                blank=True,
                null=True,
                storage=api.attachments.private_attachment_storage,
                upload_to="groups/files/",
            ),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="image_attachment",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=api.attachments.private_attachment_storage,
                upload_to="groups/images/",
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="file_attachment",
            field=models.FileField(
                blank=True,
                null=True,
                storage=api.attachments.private_attachment_storage,
                upload_to="private_chats/files/",
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="image_attachment",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=api.attachments.private_attachment_storage,
                upload_to="private_chats/images/",
            ),
        ),
    ]
