# Generated by Django 5.2.3 on 2026-08-05 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_system", models.CharField(default="ufaz", max_length=20)),
                ("default_credits", models.PositiveSmallIntegerField(default=3)),
                ("semester_goal", models.PositiveSmallIntegerField(default=85)),
                ("show_gpa", models.BooleanField(default=True)),
                ("study_goal_hours", models.PositiveSmallIntegerField(default=25)),
                ("email_notifications", models.BooleanField(default=True)),
                ("assignment_reminders", models.BooleanField(default=True)),
                ("grade_updates", models.BooleanField(default=True)),
                ("community_messages", models.BooleanField(default=True)),
                ("event_reminders", models.BooleanField(default=True)),
                ("weekly_reports", models.BooleanField(default=False)),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("followers", "People who follow me"),
                            ("nobody", "Nobody"),
                        ],
                        default="everyone",
                        max_length=20,
                    ),
                ),
                ("show_schedule", models.BooleanField(default=True)),
                ("allow_messages", models.BooleanField(default=True)),
                ("show_online_status", models.BooleanField(default=True)),
                ("theme", models.CharField(default="light", max_length=10)),
                ("language", models.CharField(default="en", max_length=10)),
                ("date_format", models.CharField(default="DD/MM/YYYY", max_length=20)),
                ("time_format", models.CharField(default="24h", max_length=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "user settings",
            },
        ),
    ]
