# Generated by Django 5.2.3 on 2026-08-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus_character',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
